### PR TITLE
[ECO-4698] Fix presence according to reference implementation

### LINKED ISSUE #1890: Fix presence implementation according to reference one (ably-go)
Looks like a lot of outdated code in the presence, needs to be updated in according to reference implementation/specs.

Related issue - https://github.com/ably/ably-cocoa/issues/1889

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4698) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by maratal**
Closes #1890

### CODE REVIEW

File: Source/ARTRealtimePresence.m [hunk 1]
```diff
@@ -780,85 +778,110 @@ - (void)reenterInternalMembers {
...
-    const BOOL syncInProgress = self.syncInProgress;
-    if (!force && syncInProgress) {
-        ARTLogDebug(_logger, @"%p \"%@\" should be removed after sync ends (syncInProgress=%d)", self, message.clientId, syncInProgress);
-        message.action = ARTPresenceAbsent;
-        // Should be removed after Sync ends
-        [self internalAdd:message withSessionId:message.syncSessionId];
-    }
-    else {
-        [_members removeObjectForKey:message.memberKey];
+- (BOOL)removeInternalMember:(ARTPresenceMessage *)message {
```
Comment (sacOO7) [inline Source/ARTRealtimePresence.m:859]: No need to return values here, since they are not being used right?

File: Source/ARTRealtimePresence.m [hunk 2]
```diff
@@ -780,85 +778,110 @@ - (void)reenterInternalMembers {
...
+    if (existing && [existing isNewerThan:message]) {
+        return false;
     }
+    _members[message.memberKey] = message;
+    return true;
 }
 
-- (void)internalRemove:(ARTPresenceMessage *)message {
-    [self internalRemove:message force:false];
+- (BOOL)addInternalMember:(ARTPresenceMessage *)message {
```
Comment (sacOO7) [inline Source/ARTRealtimePresence.m:840]: No need to return values here, since they are not being used right?

File: Source/ARTRealtimePresence.m [hunk 3]
```diff
@@ -780,85 +778,110 @@ - (void)reenterInternalMembers {
...
-    else {
-        [_members removeObjectForKey:message.memberKey];
+- (BOOL)removeInternalMember:(ARTPresenceMessage *)message {
+    ARTPresenceMessage *existing = [_internalMembers objectForKey:message.clientId];
+    if (existing && [existing isNewerThan:message]) {
+        return false;
     }
+    [_internalMembers removeObjectForKey:message.clientId];
+    return true;
 }
```
Comment (sacOO7) [inline Source/ARTRealtimePresence.m:866]:
```suggestion
- (BOOL)removeInternalMember:(ARTPresenceMessage *)incoming{
    ARTPresenceMessage *existing = [_internalMembers objectForKey:message.clientId];
    if (existing && [incoming isNewerThan:existing]) {
    [_internalMembers removeObjectForKey:message.clientId];
    }
}
```

File: Source/ARTRealtimePresence.m [hunk 4]
```diff
@@ -780,85 +778,110 @@ - (void)reenterInternalMembers {
...
-    [self internalRemove:message force:false];
+- (BOOL)addInternalMember:(ARTPresenceMessage *)message {
+    ARTPresenceMessage *existing = [_internalMembers objectForKey:message.clientId];
+    if (existing && [existing isNewerThan:message]) {
+        return false;
+    }
+    _internalMembers[message.clientId] = message;
+    ARTLogDebug(_logger, @"local member %@ with action %@ has been added", message.clientId, ARTPresenceActionToStr(message.action).uppercaseString);
+    return true;
 }
```
Comment (sacOO7) [inline Source/ARTRealtimePresence.m:848]:
```suggestion
- (BOOL)addInternalMember:(ARTPresenceMessage *)incoming{
    ARTPresenceMessage *existing = [_internalMembers objectForKey:message.clientId];
    if (existing && [incoming isNewerThan:existing]) {
    _internalMembers[message.clientId] = message;
        ARTLogDebug(_logger, @"local member %@ with action %@ has been added", message.clientId, ARTPresenceActionToStr(message.action).uppercaseString);
    }
}
```

**Review by sacOO7 — CHANGES_REQUESTED** [review]

File: Source/ARTRealtimePresence.m [hunk 5]
```diff
@@ -780,85 +778,110 @@ - (void)reenterInternalMembers {
...
 
-- (void)internalAdd:(ARTPresenceMessage *)message {
-    [self internalAdd:message withSessionId:_syncSessionId];
+    if (memberUpdated) {
+        [self broadcast:message];
+    }
+    else {
+        ARTLogDebug(_logger, @"Presence member \"%@\" with action %@ has been ignored", message.memberKey, ARTPresenceActionToStr(message.action));
+    }
+    [_beforeSyncMembers removeObjectForKey:message.memberKey]; // RTP19
```
Comment (sacOO7) [inline Source/ARTRealtimePresence.m:828]:
```suggestion

```

File: Source/ARTRealtimePresence.m [hunk 6]
```diff
@@ -780,85 +778,110 @@ - (void)reenterInternalMembers {
...
+                memberUpdated = [self removeMember:messageCopy];
+            }
+            break;
+        default:
+            break;
+    }
 
-- (void)internalAdd:(ARTPresenceMessage *)message {
-    [self internalAdd:message withSessionId:_syncSessionId];
+    if (memberUpdated) {
```
Comment (sacOO7) [inline Source/ARTRealtimePresence.m:822]:
```suggestion
    if (memberUpdated) {
        [_beforeSyncMembers removeObjectForKey:message.memberKey]; // RTP19
```

Comment (sacOO7) [reply Source/ARTRealtimePresence.m:822]: See https://github.com/ably/ably-go/pull/637/files

**Review by sacOO7 — CHANGES_REQUESTED** [review]

File: Source/ARTRealtimePresence.m (hunk 6 above)
Comment (sacOO7) [reply Source/ARTRealtimePresence.m:822]: With current implementation, even if the member is not updated, it will remove member from `_beforeSyncMembers`, hence it won't throw `leave` event at the end of the sync.

File: Source/ARTPresenceMessage.m [hunk 7]
```diff
@@ -73,25 +70,21 @@ - (NSInteger)indexFromId {
...
-    NSInteger latestIndex = [latest indexFromId];
+    NSInteger msgSerial = [self msgSerialFromId];
+    NSInteger index = [self indexFromId];
+    NSInteger otherMsgSerial = [other msgSerialFromId];
+    NSInteger otherIndex = [other indexFromId];
 
-    if (currentMsgSerial == latestMsgSerial) {
-        return currentIndex > latestIndex;
+    if (msgSerial == otherMsgSerial) {
+        return index >= otherIndex;
```
[the remark this answers is not in the document]
Comment (maratal) [reply Source/ARTPresenceMessage.m:84]: You have `>=` [there](https://github.com/ably/ably-go/blob/dd8236fc301eb078803e83efee7615f3ba133341/ably/proto_presence_message.go#L101).

File: Source/ARTRealtimePresence.m (hunk 6 above)
Comment (maratal) [reply Source/ARTRealtimePresence.m:822]: That's why it's added instead of removed upon `ARTPresenceLeave` (See RTP2f).

Comment (maratal) [reply Source/ARTRealtimePresence.m:822]: `_beforeSyncMembers` is only for tracking members that didn't receive any update at all. For them `ARTPresenceLeave` will be generated in `didRemovedMemberNoLongerPresent:`.

File: Source/ARTRealtimePresence.m (hunk 5 above)
Comment (maratal) [reply Source/ARTRealtimePresence.m:828]: see https://github.com/ably/ably-cocoa/pull/1891#discussion_r1544450746

File: Source/ARTRealtimePresence.m (hunk 1 above)
Comment (maratal) [reply Source/ARTRealtimePresence.m:859]: You use the return value [here](https://github.com/ably/ably-go/blob/dd8236fc301eb078803e83efee7615f3ba133341/ably/realtime_presence.go#L323).

File: Source/ARTRealtimePresence.m (hunk 2 above)
Comment (maratal) [reply Source/ARTRealtimePresence.m:840]: https://github.com/ably/ably-go/blob/dd8236fc301eb078803e83efee7615f3ba133341/ably/realtime_presence.go#L321

File: Source/ARTRealtimePresence.m (hunk 1 above)
Comment (maratal) [reply Source/ARTRealtimePresence.m:859]: It's used the same way in this PR.

File: Source/ARTPresenceMessage.m [hunk 8]
```diff
@@ -73,25 +70,21 @@ - (NSInteger)indexFromId {
...
-- (BOOL)isNewerThan:(ARTPresenceMessage *)latest {
-    if (latest == nil) {
-        return YES;
-    }
-
-    if ([self isSynthesized] || [latest isSynthesized]) {
-        return !self.timestamp || [latest.timestamp timeIntervalSince1970] <= [self.timestamp timeIntervalSince1970];
+- (BOOL)isNewerThan:(ARTPresenceMessage *)other {
+    if ([self isSynthesized] || [other isSynthesized]) {
+        return !self.timestamp || [other.timestamp timeIntervalSince1970] <= [self.timestamp timeIntervalSince1970];
```
[the remark this answers is not in the document]
Comment (maratal) [reply Source/ARTPresenceMessage.m]: I decided to move it to presence to avoid further confusion and denoted params to `msg1` and `msg2` as it's in ably-go. https://github.com/ably/ably-cocoa/pull/1891/commits/7ae70b3a8efd93ae93643657d7de0c2abdf4a2a1

File: Source/ARTRealtimePresence.m [hunk 9]
```diff
@@ -780,85 +778,110 @@ - (void)reenterInternalMembers {
...
-- (void)internalAdd:(ARTPresenceMessage *)message withSessionId:(NSUInteger)sessionId {
-    message.syncSessionId = sessionId;
-    [_members setObject:message forKey:message.memberKey];
-    // Local member
-    if ([message.connectionId isEqualToString:self.connectionId]) {
-        _internalMembers[message.clientId] = message;
-        ARTLogDebug(_logger, @"local member %@ with action %@ has been added", message.memberKey, ARTPresenceActionToStr(message.action).uppercaseString);
+- (BOOL)addMember:(ARTPresenceMessage *)message {
+    ARTPresenceMessage *existing = [_members objectForKey:message.memberKey];
+    if (existing && [existing isNewerThan:message]) {
```
[the remark this answers is not in the document]
Comment (maratal) [reply Source/ARTRealtimePresence.m]: https://github.com/ably/ably-cocoa/pull/1891/commits/7ae70b3a8efd93ae93643657d7de0c2abdf4a2a1

File: Source/ARTRealtimePresence.m [hunk 10]
```diff
@@ -780,85 +778,110 @@ - (void)reenterInternalMembers {
...
     }
+    _members[message.memberKey] = message;
+    return true;
 }
 
-- (void)internalRemove:(ARTPresenceMessage *)message {
-    [self internalRemove:message force:false];
+- (BOOL)addInternalMember:(ARTPresenceMessage *)message {
+    ARTPresenceMessage *existing = [_internalMembers objectForKey:message.clientId];
+    if (existing && [existing isNewerThan:message]) {
```
[the remark this answers is not in the document]
Comment (maratal) [reply Source/ARTRealtimePresence.m]: https://github.com/ably/ably-cocoa/pull/1891/commits/7ae70b3a8efd93ae93643657d7de0c2abdf4a2a1

File: Source/ARTRealtimePresence.m (hunk 1 above)
Comment (maratal) [reply Source/ARTRealtimePresence.m]: My bad, removed - https://github.com/ably/ably-cocoa/pull/1891/commits/7ae70b3a8efd93ae93643657d7de0c2abdf4a2a1

File: Source/ARTRealtimePresence.m (hunk 2 above)
Comment (maratal) [reply Source/ARTRealtimePresence.m]: https://github.com/ably/ably-cocoa/pull/1891/commits/7ae70b3a8efd93ae93643657d7de0c2abdf4a2a1

File: Source/ARTRealtimePresence.m (hunk 3 above)
Comment (maratal) [reply Source/ARTRealtimePresence.m]: https://github.com/ably/ably-cocoa/pull/1891/commits/7ae70b3a8efd93ae93643657d7de0c2abdf4a2a1

File: Source/ARTRealtimePresence.m (hunk 4 above)
Comment (maratal) [reply Source/ARTRealtimePresence.m]: https://github.com/ably/ably-cocoa/pull/1891/commits/7ae70b3a8efd93ae93643657d7de0c2abdf4a2a1

File: Source/ARTRealtimePresence.m (hunk 6 above)
Comment (sacOO7) [reply Source/ARTRealtimePresence.m:822]: I will raise a new conversation for this 👍

File: Source/ARTRealtimePresence.m [hunk 11]
```diff
@@ -780,85 +778,130 @@ - (void)reenterInternalMembers {
...
+        return !msg1.timestamp || msg1.timestamp.timeIntervalSince1970 >= msg2.timestamp.timeIntervalSince1970;
+    }
+    
+    NSInteger msg1Serial = [msg1 msgSerialFromId];
+    NSInteger msg1Index = [msg1 indexFromId];
+    NSInteger msg2Serial = [msg2 msgSerialFromId];
+    NSInteger msg2Index = [msg2 indexFromId];
+    
+    if (msg1Serial == msg2Serial) {
+        return msg1Index > msg2Index;
```
Comment (sacOO7) [inline Source/ARTRealtimePresence.m:842]:
```suggestion
        return msg1Index >= msg2Index;
```
as per https://github.com/ably/ably-go/blob/dd8236fc301eb078803e83efee7615f3ba133341/ably/proto_presence_message.go#L101

File: Source/ARTRealtimePresence.m [hunk 12]
```diff
@@ -780,85 +778,130 @@ - (void)reenterInternalMembers {
...
+        _internalMembers[message.clientId] = message;
+        ARTLogDebug(_logger, @"local member %@ with action %@ has been added", message.clientId, ARTPresenceActionToStr(message.action).uppercaseString);
     }
-    else {
-        [_members removeObjectForKey:message.memberKey];
+}
+
+- (void)removeInternalMember:(ARTPresenceMessage *)message {
+    ARTPresenceMessage *existing = [_internalMembers objectForKey:message.clientId];
+    if (!existing || [self member:message isNewerThan:existing]) {
```
Comment (sacOO7) [inline Source/ARTRealtimePresence.m:883]:
```suggestion
    if (existing && [self member:message isNewerThan:existing]) {
```

**Review by sacOO7 — CHANGES_REQUESTED** [review]

File: Source/ARTRealtimePresence.m [hunk 13]
```diff
@@ -780,85 +778,130 @@ - (void)reenterInternalMembers {
...
 
-- (void)internalAdd:(ARTPresenceMessage *)message {
-    [self internalAdd:message withSessionId:_syncSessionId];
+    if (memberUpdated) {
+        [self broadcast:message];
+    }
+    else {
+        ARTLogDebug(_logger, @"Presence member \"%@\" with action %@ has been ignored", message.memberKey, ARTPresenceActionToStr(message.action));
+    }
+    [_beforeSyncMembers removeObjectForKey:message.memberKey]; // RTP19
```
Comment (sacOO7) [inline Source/ARTRealtimePresence.m:828]: As per [RTP19](https://sdk.ably.com/builds/ably/specification/main/features/#RTP19), `_beforeSyncMembers` should only track list of members added or updated and not `leave` event. You can see the same being implemented across SDK's
[ably-go](https://github.com/ably/ably-go/blob/dd8236fc301eb078803e83efee7615f3ba133341/ably/realtime_presence.go#L318)
[ably-java](https://github.com/ably/ably-java/blob/f706160e09d639bf482474d13898933481e455b9/lib/src/main/java/io/ably/lib/realtime/Presence.java#L1056)
[ably-dotnet](https://github.com/ably/ably-dotnet/blob/f7b18f4902e42e90697e7fd35021025574edf650/src/IO.Ably.Shared/Realtime/PresenceMap.cs#L87)
None of them track/update `beforeSyncMembers` for `LEAVE` event.

**Review by sacOO7 — CHANGES_REQUESTED** [review]

File: Source/ARTRealtimePresence.m (hunk 11 above)
Comment (maratal) [reply Source/ARTRealtimePresence.m:842]: Why here is it opposite then? https://github.com/ably/ably-cocoa/pull/1891/files/1d2f015ff007537fd66febc6b28f79c7e2e37468#r1539081292

Comment (maratal) [reply Source/ARTRealtimePresence.m:842]: [RTP5f](https://sdk.ably.com/builds/ably/specification/main/features/#RTP5f) says "_any members present before and after the sync should not emit presence events, all other changes should be reflected in the PresenceMap and should emit presence events on the channel_"

which can be simplified as

"_only_members_that_changed_between_ATTACHED_states_should_result_in_presence_events_" (part of the name of the test _test__023__Presence__Channel_state_change_side_effects_...)

Making it ">=" leads to [this](https://github.com/ably/ably-cocoa/blob/35427f3120e571f5af922f68da3f99d65e668612/Test/Tests/RealtimeClientPresenceTests.swift#L840) array contains all the messages that haven't changed but still broadcasted. wdyt?

File: Source/ARTRealtimePresence.m (hunk 13 above)
Comment (maratal) [reply Source/ARTRealtimePresence.m]: https://github.com/ably/ably-cocoa/pull/1891/commits/00b04a0b020c6515d1d99dfcd8237f4d0430abe9

File: Source/ARTRealtimePresence.m (hunk 11 above)
Comment (maratal) [reply Source/ARTRealtimePresence.m:842]: Also "...[larger being newer](https://sdk.ably.com/builds/ably/specification/main/features/#RTP2b2) in both cases"

Comment (sacOO7) [reply Source/ARTRealtimePresence.m:872]: Okay, I don't think there will be same indexes for messages. So, will approve for now.
