### PR TITLE
Fix SUSPENDED channel reattach

### LINKED ISSUE #881: Realtime Channel endless loop: suspended > attached > suspended
### Which version of the Ably SDK are you using? 
`v1.1.11 - Beta 1`

### On which platform does the issue happen? 
`iOS 13`

### Which version of Xcode are you using? 
Xcode 11.1

### What did you do?
I set my iPhone to flight mode and the connection moved to disconnected as expected.
The connection retried but it always failed so it moved to DISCONNECTED state and then to SUSPENDED because it spent more time than the `connectionStateTtl` to reconnect. Channels moved to suspended too. Then, after turning off the flight mode, the connection reconnected and the channel reattached. The channel moved to ATTACHED but then the weird stuff happened. The channel entered in an endless loop: `ATTACHED -> SUSPENDED -> ATTACHING -> ATTACHED -> SUSPENDED -> ATTACHING -> ...`.

The log:

```
2019-07-26 12:06:54.917245+0100 AblyPushSwift[4493:989005] VERBOSE: R:0x2826f54a0 did receive Protocol Message Heartbeat (connection state is Connected)
2019-07-26 12:06:54.920871+0100 AblyPushSwift[4493:989005] VERBOSE: R:0x2826f54a0 heartbeat received
2019-07-26 12:07:06.686941+0100 AblyPushSwift[4493:988933] DEBUG: (ARTRealtimeChannel.m:937) R:0x2826f54a0 C:0x2820fcd20 (foo) attached or suspended and will reattach
2019-07-26 12:07:06.697132+0100 AblyPushSwift[4493:988933] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 5 - Suspended to 1 - Attaching
2019-07-26 12:07:06.705431+0100 AblyPushSwift[4493:988933] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventAttaching
2019-07-26 12:07:06.705512+0100 AblyPushSwift[4493:988933] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:07:06.705691+0100 AblyPushSwift[4493:988933] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageToDictionary {
    action = 10;
    channel = foo;
}
2019-07-26 12:07:06.711374+0100 AblyPushSwift[4493:988933] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> encoding '{
    action = 10;
    channel = foo;
}'; got: <82a76368 616e6e65 6ca3666f 6fa66163 74696f6e 0a>
2019-07-26 12:07:06.716225+0100 AblyPushSwift[4493:988933] DEBUG: (ARTRealtime.m:1083) R:0x2826f54a0 sending action 10 - Attach
2019-07-26 12:07:06.771086+0100 AblyPushSwift[4493:988933] VERBOSE: (ARTWebSocketTransport.m:339) R:0x2826f54a0 WS:0x2832d89a0 websocket did receive message
2019-07-26 12:07:06.777260+0100 AblyPushSwift[4493:988933] DEBUG: (ARTWebSocketTransport.m:365) R:0x2826f54a0 WS:0x2832d89a0 websocket in Open state did receive data <84a66163 74696f6e 0ba5666c 616773ce 001f0000 a7636861 6e6e656c a3666f6f ad636861 6e6e656c 53657269 616cb965 39315273 38535267 41613452 63383935 32373138 333a2d31>
2019-07-26 12:07:06.783810+0100 AblyPushSwift[4493:988933] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> decoding '<84a66163 74696f6e 0ba5666c 616773ce 001f0000 a7636861 6e6e656c a3666f6f ad636861 6e6e656c 53657269 616cb965 39315273 38535267 41613452 63383935 32373138 333a2d31>'; got: {
    action = 11;
    channel = foo;
    channelSerial = "e91Rs8SRgAa4Rc89527183:-1";
    flags = 2031616;
}
2019-07-26 12:07:06.789795+0100 AblyPushSwift[4493:988933] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageFromDictionary {
    action = 11;
    channel = foo;
    channelSerial = "e91Rs8SRgAa4Rc89527183:-1";
    flags = 2031616;
}
2019-07-26 12:07:06.796601+0100 AblyPushSwift[4493:988933] VERBOSE: (ARTRealtime.m:1291) R:0x2826f54a0 activity
2019-07-26 12:07:06.800389+0100 AblyPushSwift[4493:988933] VERBOSE: R:0x2826f54a0 did receive Protocol Message Attached (connection state is Connected)
2019-07-26 12:07:06.803902+0100 AblyPushSwift[4493:988933] DEBUG: (ARTRealtimeChannel.m:653) R:0x2826f54a0 C:0x2820fcd20 (foo) received channel message 11 - Attached
2019-07-26 12:07:06.807399+0100 AblyPushSwift[4493:988933] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 1 - Attaching to 2 - Attached
2019-07-26 12:07:06.810227+0100 AblyPushSwift[4493:988933] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventAttached
2019-07-26 12:07:06.810251+0100 AblyPushSwift[4493:988933] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:07:06.810328+0100 AblyPushSwift[4493:988933] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 2 - Attached to 5 - Suspended
2019-07-26 12:07:06.812331+0100 AblyPushSwift[4493:988933] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventSuspended
2019-07-26 12:07:06.812354+0100 AblyPushSwift[4493:988933] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:07:09.799294+0100 AblyPushSwift[4493:989046] VERBOSE: (ARTWebSocketTransport.m:339) R:0x2826f54a0 WS:0x2832d89a0 websocket did receive message
2019-07-26 12:07:09.811153+0100 AblyPushSwift[4493:989046] DEBUG: (ARTWebSocketTransport.m:365) R:0x2826f54a0 WS:0x2832d89a0 websocket in Open state did receive data <81a66163 74696f6e 00>
2019-07-26 12:07:09.818955+0100 AblyPushSwift[4493:989046] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> decoding '<81a66163 74696f6e 00>'; got: {
    action = 0;
}
2019-07-26 12:07:09.825166+0100 AblyPushSwift[4493:989046] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageFromDictionary {
    action = 0;
}
2019-07-26 12:07:09.832107+0100 AblyPushSwift[4493:989046] VERBOSE: (ARTRealtime.m:1291) R:0x2826f54a0 activity
2019-07-26 12:07:09.835963+0100 AblyPushSwift[4493:989046] VERBOSE: R:0x2826f54a0 did receive Protocol Message Heartbeat (connection state is Connected)
2019-07-26 12:07:09.839250+0100 AblyPushSwift[4493:989046] VERBOSE: R:0x2826f54a0 heartbeat received
2019-07-26 12:07:22.379228+0100 AblyPushSwift[4493:988933] DEBUG: (ARTRealtimeChannel.m:937) R:0x2826f54a0 C:0x2820fcd20 (foo) attached or suspended and will reattach
2019-07-26 12:07:22.383514+0100 AblyPushSwift[4493:988933] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 5 - Suspended to 1 - Attaching
2019-07-26 12:07:22.389589+0100 AblyPushSwift[4493:988933] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventAttaching
2019-07-26 12:07:22.389647+0100 AblyPushSwift[4493:988933] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:07:22.389774+0100 AblyPushSwift[4493:988933] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageToDictionary {
    action = 10;
    channel = foo;
}
2019-07-26 12:07:22.393661+0100 AblyPushSwift[4493:988933] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> encoding '{
    action = 10;
    channel = foo;
}'; got: <82a76368 616e6e65 6ca3666f 6fa66163 74696f6e 0a>
2019-07-26 12:07:22.397397+0100 AblyPushSwift[4493:988933] DEBUG: (ARTRealtime.m:1083) R:0x2826f54a0 sending action 10 - Attach
2019-07-26 12:07:22.450032+0100 AblyPushSwift[4493:988933] VERBOSE: (ARTWebSocketTransport.m:339) R:0x2826f54a0 WS:0x2832d89a0 websocket did receive message
2019-07-26 12:07:22.458986+0100 AblyPushSwift[4493:988933] DEBUG: (ARTWebSocketTransport.m:365) R:0x2826f54a0 WS:0x2832d89a0 websocket in Open state did receive data <84a66163 74696f6e 0ba5666c 616773ce 001f0000 a7636861 6e6e656c a3666f6f ad636861 6e6e656c 53657269 616cb965 39315273 38535267 41613452 63383935 32373138 333a2d31>
2019-07-26 12:07:22.467044+0100 AblyPushSwift[4493:988933] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> decoding '<84a66163 74696f6e 0ba5666c 616773ce 001f0000 a7636861 6e6e656c a3666f6f ad636861 6e6e656c 53657269 616cb965 39315273 38535267 41613452 63383935 32373138 333a2d31>'; got: {
    action = 11;
    channel = foo;
    channelSerial = "e91Rs8SRgAa4Rc89527183:-1";
    flags = 2031616;
}
2019-07-26 12:07:22.473309+0100 AblyPushSwift[4493:988933] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageFromDictionary {
    action = 11;
    channel = foo;
    channelSerial = "e91Rs8SRgAa4Rc89527183:-1";
    flags = 2031616;
}
2019-07-26 12:07:22.480585+0100 AblyPushSwift[4493:988933] VERBOSE: (ARTRealtime.m:1291) R:0x2826f54a0 activity
2019-07-26 12:07:22.484383+0100 AblyPushSwift[4493:988933] VERBOSE: R:0x2826f54a0 did receive Protocol Message Attached (connection state is Connected)
2019-07-26 12:07:22.487743+0100 AblyPushSwift[4493:988933] DEBUG: (ARTRealtimeChannel.m:653) R:0x2826f54a0 C:0x2820fcd20 (foo) received channel message 11 - Attached
2019-07-26 12:07:22.490417+0100 AblyPushSwift[4493:988933] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 1 - Attaching to 2 - Attached
2019-07-26 12:07:22.492421+0100 AblyPushSwift[4493:988933] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventAttached
2019-07-26 12:07:22.492446+0100 AblyPushSwift[4493:988933] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:07:22.492527+0100 AblyPushSwift[4493:988933] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 2 - Attached to 5 - Suspended
2019-07-26 12:07:22.494529+0100 AblyPushSwift[4493:988933] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventSuspended
2019-07-26 12:07:22.494550+0100 AblyPushSwift[4493:988933] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:07:24.852212+0100 AblyPushSwift[4493:989094] VERBOSE: (ARTWebSocketTransport.m:339) R:0x2826f54a0 WS:0x2832d89a0 websocket did receive message
2019-07-26 12:07:24.864968+0100 AblyPushSwift[4493:989094] DEBUG: (ARTWebSocketTransport.m:365) R:0x2826f54a0 WS:0x2832d89a0 websocket in Open state did receive data <81a66163 74696f6e 00>
2019-07-26 12:07:24.873389+0100 AblyPushSwift[4493:989094] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> decoding '<81a66163 74696f6e 00>'; got: {
    action = 0;
}
2019-07-26 12:07:24.879618+0100 AblyPushSwift[4493:989094] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageFromDictionary {
    action = 0;
}
2019-07-26 12:07:24.886555+0100 AblyPushSwift[4493:989094] VERBOSE: (ARTRealtime.m:1291) R:0x2826f54a0 activity
2019-07-26 12:07:24.890765+0100 AblyPushSwift[4493:989094] VERBOSE: R:0x2826f54a0 did receive Protocol Message Heartbeat (connection state is Connected)
2019-07-26 12:07:24.894869+0100 AblyPushSwift[4493:989094] VERBOSE: R:0x2826f54a0 heartbeat received
2019-07-26 12:07:39.000489+0100 AblyPushSwift[4493:989134] DEBUG: (ARTRealtimeChannel.m:937) R:0x2826f54a0 C:0x2820fcd20 (foo) attached or suspended and will reattach
2019-07-26 12:07:39.010431+0100 AblyPushSwift[4493:989134] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 5 - Suspended to 1 - Attaching
2019-07-26 12:07:39.017605+0100 AblyPushSwift[4493:989134] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventAttaching
2019-07-26 12:07:39.017687+0100 AblyPushSwift[4493:989134] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:07:39.017869+0100 AblyPushSwift[4493:989134] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageToDictionary {
    action = 10;
    channel = foo;
}
2019-07-26 12:07:39.024129+0100 AblyPushSwift[4493:989134] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> encoding '{
    action = 10;
    channel = foo;
}'; got: <82a76368 616e6e65 6ca3666f 6fa66163 74696f6e 0a>
2019-07-26 12:07:39.028910+0100 AblyPushSwift[4493:989134] DEBUG: (ARTRealtime.m:1083) R:0x2826f54a0 sending action 10 - Attach
2019-07-26 12:07:39.089981+0100 AblyPushSwift[4493:989134] VERBOSE: (ARTWebSocketTransport.m:339) R:0x2826f54a0 WS:0x2832d89a0 websocket did receive message
2019-07-26 12:07:39.096689+0100 AblyPushSwift[4493:989134] DEBUG: (ARTWebSocketTransport.m:365) R:0x2826f54a0 WS:0x2832d89a0 websocket in Open state did receive data <84a66163 74696f6e 0ba5666c 616773ce 001f0000 a7636861 6e6e656c a3666f6f ad636861 6e6e656c 53657269 616cb965 39315273 38535267 41613452 63383935 32373138 333a2d31>
2019-07-26 12:07:39.102900+0100 AblyPushSwift[4493:989134] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> decoding '<84a66163 74696f6e 0ba5666c 616773ce 001f0000 a7636861 6e6e656c a3666f6f ad636861 6e6e656c 53657269 616cb965 39315273 38535267 41613452 63383935 32373138 333a2d31>'; got: {
    action = 11;
    channel = foo;
    channelSerial = "e91Rs8SRgAa4Rc89527183:-1";
    flags = 2031616;
}
2019-07-26 12:07:39.108953+0100 AblyPushSwift[4493:989134] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageFromDictionary {
    action = 11;
    channel = foo;
    channelSerial = "e91Rs8SRgAa4Rc89527183:-1";
    flags = 2031616;
}
2019-07-26 12:07:39.116486+0100 AblyPushSwift[4493:989134] VERBOSE: (ARTRealtime.m:1291) R:0x2826f54a0 activity
2019-07-26 12:07:39.120593+0100 AblyPushSwift[4493:989134] VERBOSE: R:0x2826f54a0 did receive Protocol Message Attached (connection state is Connected)
2019-07-26 12:07:39.124324+0100 AblyPushSwift[4493:989134] DEBUG: (ARTRealtimeChannel.m:653) R:0x2826f54a0 C:0x2820fcd20 (foo) received channel message 11 - Attached
2019-07-26 12:07:39.127928+0100 AblyPushSwift[4493:989134] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 1 - Attaching to 2 - Attached
2019-07-26 12:07:39.130035+0100 AblyPushSwift[4493:989134] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventAttached
2019-07-26 12:07:39.130059+0100 AblyPushSwift[4493:989134] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:07:39.130147+0100 AblyPushSwift[4493:989134] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 2 - Attached to 5 - Suspended
2019-07-26 12:07:39.132177+0100 AblyPushSwift[4493:989134] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventSuspended
2019-07-26 12:07:39.132201+0100 AblyPushSwift[4493:989134] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:07:39.805067+0100 AblyPushSwift[4493:989166] VERBOSE: (ARTWebSocketTransport.m:339) R:0x2826f54a0 WS:0x2832d89a0 websocket did receive message
2019-07-26 12:07:39.818974+0100 AblyPushSwift[4493:989166] DEBUG: (ARTWebSocketTransport.m:365) R:0x2826f54a0 WS:0x2832d89a0 websocket in Open state did receive data <81a66163 74696f6e 00>
2019-07-26 12:07:39.828083+0100 AblyPushSwift[4493:989166] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> decoding '<81a66163 74696f6e 00>'; got: {
    action = 0;
}
2019-07-26 12:07:39.834349+0100 AblyPushSwift[4493:989166] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageFromDictionary {
    action = 0;
}
2019-07-26 12:07:39.841600+0100 AblyPushSwift[4493:989166] VERBOSE: (ARTRealtime.m:1291) R:0x2826f54a0 activity
2019-07-26 12:07:39.846237+0100 AblyPushSwift[4493:989166] VERBOSE: R:0x2826f54a0 did receive Protocol Message Heartbeat (connection state is Connected)
2019-07-26 12:07:39.850086+0100 AblyPushSwift[4493:989166] VERBOSE: R:0x2826f54a0 heartbeat received
2019-07-26 12:07:54.858142+0100 AblyPushSwift[4493:989193] VERBOSE: (ARTWebSocketTransport.m:339) R:0x2826f54a0 WS:0x2832d89a0 websocket did receive message
2019-07-26 12:07:54.869503+0100 AblyPushSwift[4493:989193] DEBUG: (ARTWebSocketTransport.m:365) R:0x2826f54a0 WS:0x2832d89a0 websocket in Open state did receive data <81a66163 74696f6e 00>
2019-07-26 12:07:54.877459+0100 AblyPushSwift[4493:989193] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> decoding '<81a66163 74696f6e 00>'; got: {
    action = 0;
}
2019-07-26 12:07:54.883601+0100 AblyPushSwift[4493:989193] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageFromDictionary {
    action = 0;
}
2019-07-26 12:07:54.890843+0100 AblyPushSwift[4493:989193] VERBOSE: (ARTRealtime.m:1291) R:0x2826f54a0 activity
2019-07-26 12:07:54.894706+0100 AblyPushSwift[4493:989193] VERBOSE: R:0x2826f54a0 did receive Protocol Message Heartbeat (connection state is Connected)
2019-07-26 12:07:54.897810+0100 AblyPushSwift[4493:989193] VERBOSE: R:0x2826f54a0 heartbeat received
2019-07-26 12:07:54.903912+0100 AblyPushSwift[4493:989193] DEBUG: (ARTRealtimeChannel.m:937) R:0x2826f54a0 C:0x2820fcd20 (foo) attached or suspended and will reattach
2019-07-26 12:07:54.905954+0100 AblyPushSwift[4493:989193] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 5 - Suspended to 1 - Attaching
2019-07-26 12:07:54.907944+0100 AblyPushSwift[4493:989193] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventAttaching
2019-07-26 12:07:54.907969+0100 AblyPushSwift[4493:989193] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:07:54.908031+0100 AblyPushSwift[4493:989193] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageToDictionary {
    action = 10;
    channel = foo;
}
2019-07-26 12:07:54.910039+0100 AblyPushSwift[4493:989193] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> encoding '{
    action = 10;
    channel = foo;
}'; got: <82a76368 616e6e65 6ca3666f 6fa66163 74696f6e 0a>
2019-07-26 12:07:54.912022+0100 AblyPushSwift[4493:989193] DEBUG: (ARTRealtime.m:1083) R:0x2826f54a0 sending action 10 - Attach
2019-07-26 12:07:54.966610+0100 AblyPushSwift[4493:989134] VERBOSE: (ARTWebSocketTransport.m:339) R:0x2826f54a0 WS:0x2832d89a0 websocket did receive message
2019-07-26 12:07:54.969829+0100 AblyPushSwift[4493:989134] DEBUG: (ARTWebSocketTransport.m:365) R:0x2826f54a0 WS:0x2832d89a0 websocket in Open state did receive data <84a66163 74696f6e 0ba5666c 616773ce 001f0000 a7636861 6e6e656c a3666f6f ad636861 6e6e656c 53657269 616cb965 39315273 38535267 41613452 63383935 32373138 333a2d31>
2019-07-26 12:07:54.972996+0100 AblyPushSwift[4493:989134] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> decoding '<84a66163 74696f6e 0ba5666c 616773ce 001f0000 a7636861 6e6e656c a3666f6f ad636861 6e6e656c 53657269 616cb965 39315273 38535267 41613452 63383935 32373138 333a2d31>'; got: {
    action = 11;
    channel = foo;
    channelSerial = "e91Rs8SRgAa4Rc89527183:-1";
    flags = 2031616;
}
2019-07-26 12:07:54.975643+0100 AblyPushSwift[4493:989134] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageFromDictionary {
    action = 11;
    channel = foo;
    channelSerial = "e91Rs8SRgAa4Rc89527183:-1";
    flags = 2031616;
}
2019-07-26 12:07:54.978834+0100 AblyPushSwift[4493:989134] VERBOSE: (ARTRealtime.m:1291) R:0x2826f54a0 activity
2019-07-26 12:07:54.980832+0100 AblyPushSwift[4493:989134] VERBOSE: R:0x2826f54a0 did receive Protocol Message Attached (connection state is Connected)
2019-07-26 12:07:54.982819+0100 AblyPushSwift[4493:989134] DEBUG: (ARTRealtimeChannel.m:653) R:0x2826f54a0 C:0x2820fcd20 (foo) received channel message 11 - Attached
2019-07-26 12:07:54.984813+0100 AblyPushSwift[4493:989134] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 1 - Attaching to 2 - Attached
2019-07-26 12:07:54.986847+0100 AblyPushSwift[4493:989134] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventAttached
2019-07-26 12:07:54.986871+0100 AblyPushSwift[4493:989134] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:07:54.986957+0100 AblyPushSwift[4493:989134] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 2 - Attached to 5 - Suspended
2019-07-26 12:07:54.988951+0100 AblyPushSwift[4493:989134] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventSuspended
2019-07-26 12:07:54.988975+0100 AblyPushSwift[4493:989134] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:08:09.808833+0100 AblyPushSwift[4493:989235] VERBOSE: (ARTWebSocketTransport.m:339) R:0x2826f54a0 WS:0x2832d89a0 websocket did receive message
2019-07-26 12:08:09.821950+0100 AblyPushSwift[4493:989235] DEBUG: (ARTWebSocketTransport.m:365) R:0x2826f54a0 WS:0x2832d89a0 websocket in Open state did receive data <81a66163 74696f6e 00>
2019-07-26 12:08:09.830497+0100 AblyPushSwift[4493:989235] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> decoding '<81a66163 74696f6e 00>'; got: {
    action = 0;
}
2019-07-26 12:08:09.836372+0100 AblyPushSwift[4493:989235] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageFromDictionary {
    action = 0;
}
2019-07-26 12:08:09.843595+0100 AblyPushSwift[4493:989235] VERBOSE: (ARTRealtime.m:1291) R:0x2826f54a0 activity
2019-07-26 12:08:09.847745+0100 AblyPushSwift[4493:989235] VERBOSE: R:0x2826f54a0 did receive Protocol Message Heartbeat (connection state is Connected)
2019-07-26 12:08:09.851354+0100 AblyPushSwift[4493:989235] VERBOSE: R:0x2826f54a0 heartbeat received
2019-07-26 12:08:11.493875+0100 AblyPushSwift[4493:989236] DEBUG: (ARTRealtimeChannel.m:937) R:0x2826f54a0 C:0x2820fcd20 (foo) attached or suspended and will reattach
2019-07-26 12:08:11.503500+0100 AblyPushSwift[4493:989236] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 5 - Suspended to 1 - Attaching
2019-07-26 12:08:11.511426+0100 AblyPushSwift[4493:989236] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventAttaching
2019-07-26 12:08:11.511513+0100 AblyPushSwift[4493:989236] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:08:11.511797+0100 AblyPushSwift[4493:989236] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageToDictionary {
    action = 10;
    channel = foo;
}
2019-07-26 12:08:11.517051+0100 AblyPushSwift[4493:989236] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> encoding '{
    action = 10;
    channel = foo;
}'; got: <82a76368 616e6e65 6ca3666f 6fa66163 74696f6e 0a>
2019-07-26 12:08:11.522033+0100 AblyPushSwift[4493:989236] DEBUG: (ARTRealtime.m:1083) R:0x2826f54a0 sending action 10 - Attach
2019-07-26 12:08:11.591783+0100 AblyPushSwift[4493:989236] VERBOSE: (ARTWebSocketTransport.m:339) R:0x2826f54a0 WS:0x2832d89a0 websocket did receive message
2019-07-26 12:08:11.600779+0100 AblyPushSwift[4493:989236] DEBUG: (ARTWebSocketTransport.m:365) R:0x2826f54a0 WS:0x2832d89a0 websocket in Open state did receive data <84a66163 74696f6e 0ba5666c 616773ce 001f0000 a7636861 6e6e656c a3666f6f ad636861 6e6e656c 53657269 616cb965 39315273 38535267 41613452 63383935 32373138 333a2d31>
2019-07-26 12:08:11.607332+0100 AblyPushSwift[4493:989236] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> decoding '<84a66163 74696f6e 0ba5666c 616773ce 001f0000 a7636861 6e6e656c a3666f6f ad636861 6e6e656c 53657269 616cb965 39315273 38535267 41613452 63383935 32373138 333a2d31>'; got: {
    action = 11;
    channel = foo;
    channelSerial = "e91Rs8SRgAa4Rc89527183:-1";
    flags = 2031616;
}
2019-07-26 12:08:11.612522+0100 AblyPushSwift[4493:989236] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageFromDictionary {
    action = 11;
    channel = foo;
    channelSerial = "e91Rs8SRgAa4Rc89527183:-1";
    flags = 2031616;
}
2019-07-26 12:08:11.619823+0100 AblyPushSwift[4493:989236] VERBOSE: (ARTRealtime.m:1291) R:0x2826f54a0 activity
2019-07-26 12:08:11.623685+0100 AblyPushSwift[4493:989236] VERBOSE: R:0x2826f54a0 did receive Protocol Message Attached (connection state is Connected)
2019-07-26 12:08:11.627229+0100 AblyPushSwift[4493:989236] DEBUG: (ARTRealtimeChannel.m:653) R:0x2826f54a0 C:0x2820fcd20 (foo) received channel message 11 - Attached
2019-07-26 12:08:11.629648+0100 AblyPushSwift[4493:989236] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 1 - Attaching to 2 - Attached
2019-07-26 12:08:11.631662+0100 AblyPushSwift[4493:989236] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventAttached
2019-07-26 12:08:11.631687+0100 AblyPushSwift[4493:989236] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:08:11.631769+0100 AblyPushSwift[4493:989236] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 2 - Attached to 5 - Suspended
2019-07-26 12:08:11.633762+0100 AblyPushSwift[4493:989236] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventSuspended
2019-07-26 12:08:11.633783+0100 AblyPushSwift[4493:989236] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:08:24.964241+0100 AblyPushSwift[4493:989237] VERBOSE: (ARTWebSocketTransport.m:339) R:0x2826f54a0 WS:0x2832d89a0 websocket did receive message
2019-07-26 12:08:24.976838+0100 AblyPushSwift[4493:989237] DEBUG: (ARTWebSocketTransport.m:365) R:0x2826f54a0 WS:0x2832d89a0 websocket in Open state did receive data <81a66163 74696f6e 00>
2019-07-26 12:08:24.985475+0100 AblyPushSwift[4493:989237] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> decoding '<81a66163 74696f6e 00>'; got: {
    action = 0;
}
2019-07-26 12:08:24.991528+0100 AblyPushSwift[4493:989237] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageFromDictionary {
    action = 0;
}
2019-07-26 12:08:24.998289+0100 AblyPushSwift[4493:989237] VERBOSE: (ARTRealtime.m:1291) R:0x2826f54a0 activity
2019-07-26 12:08:25.002262+0100 AblyPushSwift[4493:989237] VERBOSE: R:0x2826f54a0 did receive Protocol Message Heartbeat (connection state is Connected)
2019-07-26 12:08:25.005900+0100 AblyPushSwift[4493:989237] VERBOSE: R:0x2826f54a0 heartbeat received
2019-07-26 12:08:28.132489+0100 AblyPushSwift[4493:989236] DEBUG: (ARTRealtimeChannel.m:937) R:0x2826f54a0 C:0x2820fcd20 (foo) attached or suspended and will reattach
2019-07-26 12:08:28.142151+0100 AblyPushSwift[4493:989236] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 5 - Suspended to 1 - Attaching
2019-07-26 12:08:28.148236+0100 AblyPushSwift[4493:989236] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventAttaching
2019-07-26 12:08:28.148317+0100 AblyPushSwift[4493:989236] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:08:28.148492+0100 AblyPushSwift[4493:989236] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageToDictionary {
    action = 10;
    channel = foo;
}
2019-07-26 12:08:28.154371+0100 AblyPushSwift[4493:989236] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> encoding '{
    action = 10;
    channel = foo;
}'; got: <82a76368 616e6e65 6ca3666f 6fa66163 74696f6e 0a>
2019-07-26 12:08:28.158924+0100 AblyPushSwift[4493:989236] DEBUG: (ARTRealtime.m:1083) R:0x2826f54a0 sending action 10 - Attach
2019-07-26 12:08:28.219604+0100 AblyPushSwift[4493:989236] VERBOSE: (ARTWebSocketTransport.m:339) R:0x2826f54a0 WS:0x2832d89a0 websocket did receive message
2019-07-26 12:08:28.227480+0100 AblyPushSwift[4493:989236] DEBUG: (ARTWebSocketTransport.m:365) R:0x2826f54a0 WS:0x2832d89a0 websocket in Open state did receive data <84a66163 74696f6e 0ba5666c 616773ce 001f0000 a7636861 6e6e656c a3666f6f ad636861 6e6e656c 53657269 616cb965 39315273 38535267 41613452 63383935 32373138 333a2d31>
2019-07-26 12:08:28.233572+0100 AblyPushSwift[4493:989236] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> decoding '<84a66163 74696f6e 0ba5666c 616773ce 001f0000 a7636861 6e6e656c a3666f6f ad636861 6e6e656c 53657269 616cb965 39315273 38535267 41613452 63383935 32373138 333a2d31>'; got: {
    action = 11;
    channel = foo;
    channelSerial = "e91Rs8SRgAa4Rc89527183:-1";
    flags = 2031616;
}
2019-07-26 12:08:28.238897+0100 AblyPushSwift[4493:989236] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageFromDictionary {
    action = 11;
    channel = foo;
    channelSerial = "e91Rs8SRgAa4Rc89527183:-1";
    flags = 2031616;
}
2019-07-26 12:08:28.245947+0100 AblyPushSwift[4493:989236] VERBOSE: (ARTRealtime.m:1291) R:0x2826f54a0 activity
2019-07-26 12:08:28.249861+0100 AblyPushSwift[4493:989236] VERBOSE: R:0x2826f54a0 did receive Protocol Message Attached (connection state is Connected)
2019-07-26 12:08:28.253743+0100 AblyPushSwift[4493:989236] DEBUG: (ARTRealtimeChannel.m:653) R:0x2826f54a0 C:0x2820fcd20 (foo) received channel message 11 - Attached
2019-07-26 12:08:28.256065+0100 AblyPushSwift[4493:989236] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 1 - Attaching to 2 - Attached
2019-07-26 12:08:28.258075+0100 AblyPushSwift[4493:989236] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventAttached
2019-07-26 12:08:28.258096+0100 AblyPushSwift[4493:989236] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:08:28.258189+0100 AblyPushSwift[4493:989236] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 2 - Attached to 5 - Suspended
2019-07-26 12:08:28.260194+0100 AblyPushSwift[4493:989236] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventSuspended
2019-07-26 12:08:28.260215+0100 AblyPushSwift[4493:989236] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:08:39.914311+0100 AblyPushSwift[4493:989294] VERBOSE: (ARTWebSocketTransport.m:339) R:0x2826f54a0 WS:0x2832d89a0 websocket did receive message
2019-07-26 12:08:39.926914+0100 AblyPushSwift[4493:989294] DEBUG: (ARTWebSocketTransport.m:365) R:0x2826f54a0 WS:0x2832d89a0 websocket in Open state did receive data <81a66163 74696f6e 00>
2019-07-26 12:08:39.934798+0100 AblyPushSwift[4493:989294] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> decoding '<81a66163 74696f6e 00>'; got: {
    action = 0;
}
2019-07-26 12:08:39.940762+0100 AblyPushSwift[4493:989294] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageFromDictionary {
    action = 0;
}
2019-07-26 12:08:39.948164+0100 AblyPushSwift[4493:989294] VERBOSE: (ARTRealtime.m:1291) R:0x2826f54a0 activity
2019-07-26 12:08:39.952880+0100 AblyPushSwift[4493:989294] VERBOSE: R:0x2826f54a0 did receive Protocol Message Heartbeat (connection state is Connected)
2019-07-26 12:08:39.956281+0100 AblyPushSwift[4493:989294] VERBOSE: R:0x2826f54a0 heartbeat received
2019-07-26 12:08:44.754314+0100 AblyPushSwift[4493:989299] DEBUG: (ARTRealtimeChannel.m:937) R:0x2826f54a0 C:0x2820fcd20 (foo) attached or suspended and will reattach
2019-07-26 12:08:44.763707+0100 AblyPushSwift[4493:989299] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 5 - Suspended to 1 - Attaching
2019-07-26 12:08:44.770267+0100 AblyPushSwift[4493:989299] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventAttaching
2019-07-26 12:08:44.770348+0100 AblyPushSwift[4493:989299] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:08:44.770573+0100 AblyPushSwift[4493:989299] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageToDictionary {
    action = 10;
    channel = foo;
}
2019-07-26 12:08:44.776910+0100 AblyPushSwift[4493:989299] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> encoding '{
    action = 10;
    channel = foo;
}'; got: <82a76368 616e6e65 6ca3666f 6fa66163 74696f6e 0a>
2019-07-26 12:08:44.781901+0100 AblyPushSwift[4493:989299] DEBUG: (ARTRealtime.m:1083) R:0x2826f54a0 sending action 10 - Attach
2019-07-26 12:08:44.845809+0100 AblyPushSwift[4493:989299] VERBOSE: (ARTWebSocketTransport.m:339) R:0x2826f54a0 WS:0x2832d89a0 websocket did receive message
2019-07-26 12:08:44.854624+0100 AblyPushSwift[4493:989299] DEBUG: (ARTWebSocketTransport.m:365) R:0x2826f54a0 WS:0x2832d89a0 websocket in Open state did receive data <84a66163 74696f6e 0ba5666c 616773ce 001f0000 a7636861 6e6e656c a3666f6f ad636861 6e6e656c 53657269 616cb965 39315273 38535267 41613452 63383935 32373138 333a2d31>
2019-07-26 12:08:44.860912+0100 AblyPushSwift[4493:989299] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> decoding '<84a66163 74696f6e 0ba5666c 616773ce 001f0000 a7636861 6e6e656c a3666f6f ad636861 6e6e656c 53657269 616cb965 39315273 38535267 41613452 63383935 32373138 333a2d31>'; got: {
    action = 11;
    channel = foo;
    channelSerial = "e91Rs8SRgAa4Rc89527183:-1";
    flags = 2031616;
}
2019-07-26 12:08:44.866949+0100 AblyPushSwift[4493:989299] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageFromDictionary {
    action = 11;
    channel = foo;
    channelSerial = "e91Rs8SRgAa4Rc89527183:-1";
    flags = 2031616;
}
2019-07-26 12:08:44.874095+0100 AblyPushSwift[4493:989299] VERBOSE: (ARTRealtime.m:1291) R:0x2826f54a0 activity
2019-07-26 12:08:44.877861+0100 AblyPushSwift[4493:989299] VERBOSE: R:0x2826f54a0 did receive Protocol Message Attached (connection state is Connected)
2019-07-26 12:08:44.881324+0100 AblyPushSwift[4493:989299] DEBUG: (ARTRealtimeChannel.m:653) R:0x2826f54a0 C:0x2820fcd20 (foo) received channel message 11 - Attached
2019-07-26 12:08:44.883991+0100 AblyPushSwift[4493:989299] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 1 - Attaching to 2 - Attached
2019-07-26 12:08:44.885997+0100 AblyPushSwift[4493:989299] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventAttached
2019-07-26 12:08:44.886019+0100 AblyPushSwift[4493:989299] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:08:44.886101+0100 AblyPushSwift[4493:989299] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 2 - Attached to 5 - Suspended
2019-07-26 12:08:44.888119+0100 AblyPushSwift[4493:989299] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventSuspended
2019-07-26 12:08:44.888140+0100 AblyPushSwift[4493:989299] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:08:54.864392+0100 AblyPushSwift[4493:989300] VERBOSE: (ARTWebSocketTransport.m:339) R:0x2826f54a0 WS:0x2832d89a0 websocket did receive message
2019-07-26 12:08:54.877422+0100 AblyPushSwift[4493:989300] DEBUG: (ARTWebSocketTransport.m:365) R:0x2826f54a0 WS:0x2832d89a0 websocket in Open state did receive data <81a66163 74696f6e 00>
2019-07-26 12:08:54.885826+0100 AblyPushSwift[4493:989300] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> decoding '<81a66163 74696f6e 00>'; got: {
    action = 0;
}
2019-07-26 12:08:54.891888+0100 AblyPushSwift[4493:989300] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageFromDictionary {
    action = 0;
}
2019-07-26 12:08:54.899800+0100 AblyPushSwift[4493:989300] VERBOSE: (ARTRealtime.m:1291) R:0x2826f54a0 activity
2019-07-26 12:08:54.903757+0100 AblyPushSwift[4493:989300] VERBOSE: R:0x2826f54a0 did receive Protocol Message Heartbeat (connection state is Connected)
2019-07-26 12:08:54.907047+0100 AblyPushSwift[4493:989300] VERBOSE: R:0x2826f54a0 heartbeat received
2019-07-26 12:09:01.394445+0100 AblyPushSwift[4493:989237] DEBUG: (ARTRealtimeChannel.m:937) R:0x2826f54a0 C:0x2820fcd20 (foo) attached or suspended and will reattach
2019-07-26 12:09:01.403898+0100 AblyPushSwift[4493:989237] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 5 - Suspended to 1 - Attaching
2019-07-26 12:09:01.410721+0100 AblyPushSwift[4493:989237] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventAttaching
2019-07-26 12:09:01.410826+0100 AblyPushSwift[4493:989237] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:09:01.411027+0100 AblyPushSwift[4493:989237] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageToDictionary {
    action = 10;
    channel = foo;
}
2019-07-26 12:09:01.417227+0100 AblyPushSwift[4493:989237] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> encoding '{
    action = 10;
    channel = foo;
}'; got: <82a76368 616e6e65 6ca3666f 6fa66163 74696f6e 0a>
2019-07-26 12:09:01.422162+0100 AblyPushSwift[4493:989237] DEBUG: (ARTRealtime.m:1083) R:0x2826f54a0 sending action 10 - Attach
2019-07-26 12:09:01.482530+0100 AblyPushSwift[4493:989237] VERBOSE: (ARTWebSocketTransport.m:339) R:0x2826f54a0 WS:0x2832d89a0 websocket did receive message
2019-07-26 12:09:01.488814+0100 AblyPushSwift[4493:989237] DEBUG: (ARTWebSocketTransport.m:365) R:0x2826f54a0 WS:0x2832d89a0 websocket in Open state did receive data <84a66163 74696f6e 0ba5666c 616773ce 001f0000 a7636861 6e6e656c a3666f6f ad636861 6e6e656c 53657269 616cb965 39315273 38535267 41613452 63383935 32373138 333a2d31>
2019-07-26 12:09:01.495039+0100 AblyPushSwift[4493:989237] DEBUG: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack> decoding '<84a66163 74696f6e 0ba5666c 616773ce 001f0000 a7636861 6e6e656c a3666f6f ad636861 6e6e656c 53657269 616cb965 39315273 38535267 41613452 63383935 32373138 333a2d31>'; got: {
    action = 11;
    channel = foo;
    channelSerial = "e91Rs8SRgAa4Rc89527183:-1";
    flags = 2031616;
}
2019-07-26 12:09:01.499725+0100 AblyPushSwift[4493:989237] VERBOSE: RS:0x282bf6d90 ARTJsonLikeEncoder<msgpack>: protocolMessageFromDictionary {
    action = 11;
    channel = foo;
    channelSerial = "e91Rs8SRgAa4Rc89527183:-1";
    flags = 2031616;
}
2019-07-26 12:09:01.506747+0100 AblyPushSwift[4493:989237] VERBOSE: (ARTRealtime.m:1291) R:0x2826f54a0 activity
2019-07-26 12:09:01.510453+0100 AblyPushSwift[4493:989237] VERBOSE: R:0x2826f54a0 did receive Protocol Message Attached (connection state is Connected)
2019-07-26 12:09:01.513984+0100 AblyPushSwift[4493:989237] DEBUG: (ARTRealtimeChannel.m:653) R:0x2826f54a0 C:0x2820fcd20 (foo) received channel message 11 - Attached
2019-07-26 12:09:01.516216+0100 AblyPushSwift[4493:989237] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 1 - Attaching to 2 - Attached
2019-07-26 12:09:01.518212+0100 AblyPushSwift[4493:989237] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660-ARTChannelEventAttached
2019-07-26 12:09:01.518235+0100 AblyPushSwift[4493:989237] VERBOSE: PublicEventEmitter Notification emitted 0x283aeb660
2019-07-26 12:09:01.518315+0100 AblyPushSwift[4493:989237] DEBUG: (ARTRealtimeChannel.m:597) R:0x2826f54a0 C:0x2820fcd20 (foo) channel state transitions from 2 - Attached to 5 - Suspended
```

### PR DESCRIPTION
**Pull request by ricardopereira**
Fixes #881.

### CODE REVIEW

**Comment by ricardopereira** [comment]
Cherry picked fix done in another PR: 3cbca52.

File: Source/ARTRealtimeChannel.m [hunk 1]
```diff
@@ -989,9 +989,12 @@ - (void)setSuspended:(ARTStatus *)status retryIn:(NSTimeInterval)retryTimeout {
     [self failQueuedMessages:status];
     [self transition:ARTRealtimeChannelSuspended status:status];
     [[self unlessStateChangesBefore:retryTimeout do:^{
+        [self.realtime.logger debug:__FILE__ line:__LINE__ message:@"RT:%p C:%p (%@) reattach initiated by retry timeout", self->_realtime, self, self.name];
         [self reattachWithReason:nil callback:^(ARTErrorInfo *errorInfo) {
-            ARTStatus *status = [ARTStatus state:ARTStateError info:errorInfo];
-            [self setSuspended:status];
+            if (errorInfo) {
```
Comment (SimonWoolf) [inline Source/ARTRealtimeChannel.m]: > unlessStateChangesBefore:retryTimeout do

Why are we still setting the retry timeout unconditionally when we go into suspended?

In particular, if a channel goes into suspended as a side effect of a connection state change, it should not have any kind of independent retry timeout of its own volition; it should just sit there doing nothing until the connection state becomes CONNECTED, at which time it should have the side effect of triggering all `suspended` channels to reattach (RTL3d). 

The independent channel suspended retry timer from [RTL13](https://docs.ably.io/client-lib-development-guide/features/#RTL13) is only for if the channel refuses to become attached _while the connection is connected_, per rtl4f. E.g. cf https://github.com/ably/ably-js/blob/master/common/lib/client/realtimechannel.js#L414

Comment (ricardopereira) [reply Source/ARTRealtimeChannel.m]: @SimonWoolf Fixed with 45c21e4.

**Comment by ricardopereira** [comment]
@SimonWoolf Please review the last parts. Thanks
