### PR TITLE
Bring `ARTClientOptions#agents` in line with spec

### LINKED ISSUE #1525: Ably `agents` client option is implemented incorrectly
As observed in https://github.com/ably/ably-asset-tracking-common/pull/66#issuecomment-1309993388.

Under this issue:

1. Remove the `addAgent:version` method from `ARTClientOptions`
2. Refactor the `agents` method from `ARTClientOptions` to make it a property, akin to `transportParams`
3. Release as a breaking change in a `1.2` series `patch` release, which is ok per [our guidance around adoption of SemVer](https://github.com/ably/engineering/blob/main/sdk/versioning.md#semantic-versioning)

At that point we can update Ably SDK implementations to use this new implementation.

### PR DESCRIPTION
**Pull request by lawrence-forooghian**
This removes the non-spec `-[ARTClientOptions addAgent:version:]` and replaces it with a dictionary `-agents` property, hence implementing [RSC7d6](https://sdk.ably.com/builds/ably/specification/main/features/#RSC7d6) as described by the spec.

Closes #1525.

### CODE REVIEW

File: Source/ARTClientOptions.m [hunk 1]
```diff
@@ -224,21 +222,23 @@ - (NSString *)host:(NSString *)host forEnvironment:(NSString *)environment {
...
-}
-
-- (NSString *)agents {
+- (NSString *)agentLibraryIdentifier {
     NSMutableString *agents = [NSMutableString string];
     [agents appendFormat:@"%@ ", [ARTDefault libraryAgent]];
-    for (NSString *agent in _additionalAgents) {
-        [agents appendFormat:@"%@ ", agent];
+    
+    // We sort the agent names so that we have a predictable order when testing.
```
Comment (maratal) [inline Source/ARTClientOptions.m:229]: Isn't the order of appending the most predictable?

**Review by maratal — APPROVED** [review]
LGTM
