### PR TITLE
Fix internet-up.ably-realtime.com checks

### LINKED ISSUE #931: Flaky test: RTN17* (fallback hosts)
```
[10:56:12]: ▸     ✗ Connection__Host_Fallback__should_retry_hosts_in_random_order_after_checkin_if_an_internet_connection_is_available, expected to have Array<NSURL> with count 6, got 7
[10:56:12]: ▸     ✗ Connection__Host_Fallback__should_retry_hosts_in_random_order_after_checkin_if_an_internet_connection_is_available, expected to equal <[d.ably-realtime.com, e.ably-realtime.com, a.ably-realtime.com, c.ably-realtime.com, b.ably-realtime.com]>, got <[d.ably-realtime.com, a.ably-realtime.com, d.ably-realtime.com, c.ably-realtime.com, b.ably-realtime.com, e.ably-realtime.com]>
```

```
[09:38:12]: ▸     ✗ Connection__Host_Fallback__should_retry_custom_fallback_hosts_in_random_order_after_checkin_if_an_internet_connection_is_available, expected to have Array<NSURL> with count 6, got 7
[09:38:12]: ▸     ✗ Connection__Host_Fallback__should_retry_custom_fallback_hosts_in_random_order_after_checkin_if_an_internet_connection_is_available, expected to equal <[i.ably-realtime.com, j.ably-realtime.com, f.ably-realtime.com, h.ably-realtime.com, g.ably-realtime.com]>, got <[i.ably-realtime.com, f.ably-realtime.com, i.ably-realtime.com, h.ably-realtime.com, g.ably-realtime.com, j.ably-realtime.com]>
```

The test suite tries to arrange things so that the order is always [a given](https://github.com/ably/ably-cocoa/blob/a89a864cd9c6ec0c881eaa034ba7de2d947dadf0/Spec/RealtimeClientConnection.swift#L3143) 3, 4, 0, 2, 1, but then we see tests where it's sometimes 3, 0, 3, 2, 1, 4 (notice there's one more than expected).

I can't reproduce this on my machine, so the flakiness probably has to do with Travis limited system resources.

### LINKED ISSUE #952: Result of internet-up.ably-realtime.com is ignored
[RTN17c](https://docs.ably.io/client-lib-development-guide/features/#RTN17c):

> [...] the Connection manager should first check if an internet connection is available by issuing a GET request to https://internet-up.ably-realtime.com/is-the-internet-up.txt. If the request succeeds and the text “yes” is included in the body, then the client library can assume it has a viable internet connection and should then immediately retry the connection [...]

But we're retrying whether the request succeeds or not.

### PR DESCRIPTION
**Pull request by tcard**
Run them on each fallback host change, and don't ignore the result.

Fixes #952.

Commit acdb52c supersedes #959 and fixes #931.

### CODE REVIEW

File: Spec/RealtimeClientConnection.swift [hunk 1]
```diff
@@ -3560,16 +3560,19 @@ class RealtimeClientConnection: QuickSpec {
                     TestProxyTransport.network = .hostUnreachable
                     defer { TestProxyTransport.network = nil }
 
-                    var urlConnections = [NSURL]()
+                    var urls = [NSURL]()
```
Comment (ricardopereira) [inline Spec/RealtimeClientConnection.swift]: We can just use `URL` instead of `NSURL` and avoid those casts.

File: Spec/RealtimeClientConnection.swift [hunk 2]
```diff
@@ -3580,18 +3583,86 @@ class RealtimeClientConnection: QuickSpec {
...
+                    var resultFallbackHosts = [String]()
+                    var gotInternetIsUpCheck = false
+                    for url in urls {
+                        if NSRegularExpression.match(url.absoluteString, pattern: "//internet-up.ably-realtime.com/is-the-internet-up.txt") {
+                            gotInternetIsUpCheck = true
+                        } else if let fallbackHost = extractHostname(url) {
+                            if Optional(fallbackHost) == resultFallbackHosts.last {
+                                continue
+                            }
+                            // Host changed; should've had a internet check before.
```
Comment (ricardopereira) [inline Spec/RealtimeClientConnection.swift]: Small typo: "should've had a internet"

File: Spec/RealtimeClientConnection.swift [hunk 3]
```diff
@@ -3580,18 +3583,86 @@ class RealtimeClientConnection: QuickSpec {
...
+                    }
+                    
+                    waitUntil(timeout: testTimeout) { done in
+                        // wss://[a-e].ably-realtime.com: when a timeout occurs
+                        client.connection.once(.disconnected) { error in
+                            done()
+                        }
+                        // wss://[a-e].ably-realtime.com: when a 401 occurs because of the `xxxx:xxxx` key
+                        client.connection.once(.failed) { error in
+                            done()
```
Comment (ricardopereira) [inline Spec/RealtimeClientConnection.swift]: Does this need a `partialDone`?

Comment (tcard) [reply Spec/RealtimeClientConnection.swift]: The connection is going to get either to DISCONNECTED or to FAILED. Anyway, it was this way before.

File: Spec/RealtimeClientConnection.swift (hunk 2 above)
Comment (tcard) [reply Spec/RealtimeClientConnection.swift]: Fixed at 147d7b7a1944243244b0d5b2ea2ee95a2c414781.

File: Spec/RealtimeClientConnection.swift (hunk 1 above)
Comment (tcard) [reply Spec/RealtimeClientConnection.swift]: Fixed at b13ddb51b7c159e6f784ee0f837f1d9910377922.

**Comment by tcard** [comment]
CI is failing (sometimes):

```
[22:54:51]: ▸     ✗ Connection__Host_Fallback__applies_when_the_default_realtime_ably_io_endpoint_is_being_used, expected to have Array<URL> with count 2, got 1
[22:54:51]: ▸     ✗ Connection__Host_Fallback__applies_when_an_array_of_ClientOptions_fallbackHosts_is_provided, expected to be true, got <false>
[22:54:51]: ▸     ✗ Connection__Host_Fallback__every_connection_is_first_attempted_to_the_primary_host_realtime_ably_io, Waited more than 10.0 seconds
[22:54:51]: ▸     ✗ Connection__Host_Fallback__every_connection_is_first_attempted_to_the_primary_host_realtime_ably_io, expected to have Array<URL> with count 3, got 2
[22:54:51]: ▸     ✗ Connection__Host_Fallback__every_connection_is_first_attempted_to_the_primary_host_realtime_ably_io, expected to be true, got <false>
[22:54:51]: ▸     ✗ Connection__Host_Fallback__every_connection_is_first_attempted_to_the_primary_host_realtime_ably_io, Test crashed
[22:54:51]: ▸     ✗ Connection__Host_Fallback__should_retry_hosts_in_random_order_after_checkin_if_an_internet_connection_is_available, expected to equal <[d.ably-realtime.com, e.ably-realtime.com, a.ably-realtime.com, c.ably-realtime.com, b.ably-realtime.com]>, got <[d.ably-realtime.com, e.ably-realtime.com, a.ably-realtime.com, c.ably-realtime.com]>
```

```
[22:37:02]: ▸     ✗ Connection__Host_Fallback__should_retry_hosts_in_random_order_after_checkin_if_an_internet_connection_is_available, expected to be true, got <false>
```

**Comment by ricardopereira** [comment]
@tcard Does the CI pass in your machine?

**Comment by tcard** [comment]
> @tcard Does the CI pass in your machine?

It does, but this really is failing too much on CI. I'll come back to this at some point.

**Comment by tcard** [comment]
CI failures seem unrelated to this fix and just seem related to the general theme of Travis just _hanging_ for too long.

**Comment by tcard** [comment]
Bitrise says this is [✅](https://app.bitrise.io/build/d96e75a8d9eeade0#?tab=log).

@ricardopereira PTAL, GitHub dismissed your review after a merge commit.
