### PR TITLE
Copy channels for public iterate() on internal queue.

### LINKED ISSUE #918: Channels mutated-while-enumerated crash
While [soak testing](https://github.com/ably/ably-cocoa/pull/916#issuecomment-554733864), the following happened:

```
2019-11-17 10:44:07.438927+0100 Ably-SoakTest-AppUITests-Runner[72504:1078116] *** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSDictionaryM: 0x600000ac50e0> was mutated while being enumerated.'
*** First throw call stack:
(
    0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
    1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
    2   CoreFoundation                      0x00007fff23c4bf00 +[__NSFastEnumerationEnumerator allocWithZone:] + 0
    3   CoreFoundation                      0x00007fff23c4c067 -[__NSFastEnumerationEnumerator nextObject] + 167
    4   CoreFoundation                      0x00007fff23cd8299 -[__NSDictionaryObjectEnumerator nextObject] + 57
    5   CoreFoundation                      0x00007fff23c4be53 -[NSEnumerator countByEnumeratingWithState:objects:count:] + 51
    6   Ably                                0x000000010bc91bcf -[ARTRealtimeInternal transitionSideEffects:] + 9903
    7   Ably                                0x000000010bc8eb69 -[ARTRealtimeInternal transition:withErrorInfo:] + 905
    8   Ably                                0x000000010bc964b6 -[ARTRealtimeInternal onError:] + 1222
    9   Ably                                0x000000010bca3399 -[ARTRealtimeInternal realtimeTransport:didReceiveMessage:] + 2121
    10  Ably                                0x000000010bc338aa -[ARTWebSocketTransport receive:] + 218
    11  Ably                                0x000000010bc36d09 -[ARTWebSocketTransport webSocketMessageProtocol:] + 345
    12  Ably                                0x000000010bc366b4 -[ARTWebSocketTransport webSocket:didReceiveMessage:] + 772
    13  Ably-SoakTest-AppUITests            0x000000010bb513b9 $s24Ably_SoakTest_AppUITests0bC9WebSocketC15messageToClient6action5setUpySo24ARTProtocolMessageActionV_ySo0nO0CXEtF + 425
    14  Ably-SoakTest-AppUITests            0x000000010bb4ff9a $s24Ably_SoakTest_AppUITests0bC9WebSocketC4openyyFyycfU_yycfU_ + 346
    15  Ably-SoakTest-AppUITests            0x000000010bb560bf $s24Ably_SoakTest_AppUITests0bC9WebSocketC13doIfStillOpen19afterSecondsBetween7executeySNySdG_yyctFyycfU_ + 271
    16  Ably-SoakTest-AppUITests            0x000000010bb5373d $sIeg_IeyB_TR + 45
    17  libdispatch.dylib                   0x00007fff519de7b9 _dispatch_client_callout + 8
    18  libdispatch.dylib                   0x00007fff519e0b75 _dispatch_continuation_pop + 440
    19  libdispatch.dylib                   0x00007fff519f19cc _dispatch_source_invoke + 1997
    20  libdispatch.dylib                   0x00007fff519e4394 _dispatch_lane_serial_drain + 305
    21  libdispatch.dylib                   0x00007fff519e4f5c _dispatch_lane_invoke + 388
    22  libdispatch.dylib                   0x00007fff519eeff9 _dispatch_workloop_worker_thread + 626
    23  libsystem_pthread.dylib             0x00007fff51bfd611 _pthread_wqthread + 421
    24  libsystem_pthread.dylib             0x00007fff51bfd3fd start_wqthread + 13
)
```

### PR DESCRIPTION
**Pull request by tcard**
We were getting the iterator in the internal queue, but then doing the
copy into public wrappers in the caller's queue. So the internal queue
could then concurrently run a task that mutates the collection while
it's being copied.

Now the copying is done while still on the internal queue, on the common
ARTChannels; Rest and Realtime just provide mappers to copy into the
right public channel type.

Fixes #918 (probably?).

### CODE REVIEW

**Comment by tcard** [comment]
While #918 could (as far as I can tell) be caused by this too, the actual bug triggered by #916 is deterministic and is fixed by #920.

File: Source/ARTChannels.h [hunk 1]
```diff
@@ -18,6 +18,6 @@
 - (ChannelType)get:(NSString *)name;
 - (ChannelType)get:(NSString *)name options:(ARTChannelOptions *)options;
 - (void)release:(NSString *)name;
-- (id<NSFastEnumeration>)iterate;
+- (id<NSFastEnumeration>)copyIntoIteratorWithMapper:(id (^)(ChannelType))mapper;
```
Comment (QuintinWillison) [inline Source/ARTChannels.h]: I'm not clear whether this is a user API. Is this a breaking change?

Comment (tcard) [reply Source/ARTChannels.h]: No, it isn't. ARTChannels is used internally by ARTRealtimeChannelsInternal and ARTRestChannelsInternal. The exposed method is still `iterate`.

**Comment by tcard** [comment]
@QuintinWillison Anything outstanding here?

File: Source/ARTChannels.h (hunk 1 above)
Comment (QuintinWillison) [reply Source/ARTChannels.h]: Thanks for explaining.
