### PR TITLE
[ECO-4228] Re-enable skipped presence tests

### LINKED ISSUE #1876: Re-enable skipped presence tests
A lot of presence skipped due to constant failing. Need to investigate into them more deeply after merging protocol [v2](https://github.com/ably/ably-cocoa/pull/1714).

### PR DESCRIPTION
**Pull request by maratal**
Closes #1876 

In this PR I first removed "skipped" from all presence tests and ran it locally. Those that didn't fail ended up in a [loop](https://test-observability.herokuapp.com/repos/ably/ably-cocoa/uploads?branches[]=fix%2F1848-refactoring-presence-looped) a few times. Those that failed twice or more were skipped again. Two tests failed once (051 and 030) and I left them active. I've also left FLAKY label for visibility ([temporarily](https://github.com/ably/ably-cocoa/issues/1887)).

Read commit messages for more. In total 12 (out of 33) presence tests were unskipped.

### CODE REVIEW

File: Test/Tests/RealtimeClientPresenceTests.swift [hunk 1]
```diff
@@ -128,7 +128,7 @@ class RealtimeClientPresenceTests: XCTestCase {
         XCTAssertFalse(channel.internal.presence.syncComplete)
     }
 
-    func skipped__test__010__Presence__ProtocolMessage_bit_flag__when_members_are_present() throws {
+    func test__FLAKY__010__Presence__ProtocolMessage_bit_flag__when_members_are_present() throws {
```
Comment (sacOO7) [inline Test/Tests/RealtimeClientPresenceTests.swift:131]: We should be renaming tests now right? `FLAKY` keyward can be removed if they are not flaky anymore wdyt

**Review by sacOO7 — CHANGES_REQUESTED** [review]

**Comment by sacOO7** [comment]
I strongly feel we should unskip/fix most of / all of presence tests. Those are needed to make sure protocol 2.0 / no connection serial works as expected. We did the same for ably-java sometime back https://github.com/ably/ably-java/pull/989

File: Test/Tests/RealtimeClientPresenceTests.swift (hunk 1 above)
Comment (maratal) [reply Test/Tests/RealtimeClientPresenceTests.swift:131]: I wanted to do it [later](https://github.com/ably/ably-cocoa/issues/1887) when absolutely sure they are alright.

**Review by umair-ably — APPROVED** [review]
I'm happy for the flaky keyword to be removed later

**Comment by maratal** [comment]
> I strongly feel we should unskip/fix most of / all of presence tests. Those are needed to make sure protocol 2.0 / no connection serial works as expected. We did the same for ably-java sometime back [ably/ably-java#989](https://github.com/ably/ably-java/pull/989)

This may require a lot of effort for each test. This PR contains only tests that just started working normally again at some point. So I've created an umbrella issue for the rest of the presence tests - https://github.com/ably/ably-cocoa/issues/1889
