### PR TITLE
Move channels to FAILED only after their iterator is done. 

### LINKED ISSUE #918: Channels mutated-while-enumerated crash
While [soak testing](https://github.com/ably/ably-cocoa/pull/916#issuecomment-554733864), the following happened:

```
2019-11-17 10:44:07.438927+0100 Ably-SoakTest-AppUITests-Runner[72504:1078116] *** Terminating app due to uncaught exception 'NSGenericException', reason: '*** Collection <__NSDictionaryM: 0x600000ac50e0> was mutated while being enumerated.'
*** First throw call stack:
(
    0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
    1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
    2   CoreFoundation                      0x00007fff23c4bf00 +[__NSFastEnumerationEnumerator allocWithZone:] + 0
    3   CoreFoundation                      0x00007fff23c4c067 -[__NSFastEnumerationEnumerator nextObject] + 167
    4   CoreFoundation                      0x00007fff23cd8299 -[__NSDictionaryObjectEnumerator nextObject] + 57
    5   CoreFoundation                      0x00007fff23c4be53 -[NSEnumerator countByEnumeratingWithState:objects:count:] + 51
    6   Ably                                0x000000010bc91bcf -[ARTRealtimeInternal transitionSideEffects:] + 9903
    7   Ably                                0x000000010bc8eb69 -[ARTRealtimeInternal transition:withErrorInfo:] + 905
    8   Ably                                0x000000010bc964b6 -[ARTRealtimeInternal onError:] + 1222
    9   Ably                                0x000000010bca3399 -[ARTRealtimeInternal realtimeTransport:didReceiveMessage:] + 2121
    10  Ably                                0x000000010bc338aa -[ARTWebSocketTransport receive:] + 218
    11  Ably                                0x000000010bc36d09 -[ARTWebSocketTransport webSocketMessageProtocol:] + 345
    12  Ably                                0x000000010bc366b4 -[ARTWebSocketTransport webSocket:didReceiveMessage:] + 772
    13  Ably-SoakTest-AppUITests            0x000000010bb513b9 $s24Ably_SoakTest_AppUITests0bC9WebSocketC15messageToClient6action5setUpySo24ARTProtocolMessageActionV_ySo0nO0CXEtF + 425
    14  Ably-SoakTest-AppUITests            0x000000010bb4ff9a $s24Ably_SoakTest_AppUITests0bC9WebSocketC4openyyFyycfU_yycfU_ + 346
    15  Ably-SoakTest-AppUITests            0x000000010bb560bf $s24Ably_SoakTest_AppUITests0bC9WebSocketC13doIfStillOpen19afterSecondsBetween7executeySNySdG_yyctFyycfU_ + 271
    16  Ably-SoakTest-AppUITests            0x000000010bb5373d $sIeg_IeyB_TR + 45
    17  libdispatch.dylib                   0x00007fff519de7b9 _dispatch_client_callout + 8
    18  libdispatch.dylib                   0x00007fff519e0b75 _dispatch_continuation_pop + 440
    19  libdispatch.dylib                   0x00007fff519f19cc _dispatch_source_invoke + 1997
    20  libdispatch.dylib                   0x00007fff519e4394 _dispatch_lane_serial_drain + 305
    21  libdispatch.dylib                   0x00007fff519e4f5c _dispatch_lane_invoke + 388
    22  libdispatch.dylib                   0x00007fff519eeff9 _dispatch_workloop_worker_thread + 626
    23  libsystem_pthread.dylib             0x00007fff51bfd611 _pthread_wqthread + 421
    24  libsystem_pthread.dylib             0x00007fff51bfd3fd start_wqthread + 13
)
```

### PR DESCRIPTION
**Pull request by tcard**
The move to FAILED triggers the detached event emitter, which in turn
can cause .release() to remove the channel from the collection. If this
is done while channels are being iterated, that's iterator invalidation
which can cause a crash.

Fixes #918.

### CODE REVIEW

File: Source/ARTRealtime.m [hunk 1]
```diff
@@ -707,7 +707,15 @@ - (ARTEventListener *)transitionSideEffects:(ARTConnectionStateChange *)stateCha
...
         [self failQueuedMessages:channelStatus];
-        // For every Channel
+        
+        // If there's a channels.release() going on waiting on this channel
+        // to detach, failing it here would fire its event listener and
+        // immediately removing the channel from the channels dictionary, thus
+        // invalidating the iterator and causing a crashing.
+        //
+        // So fail later, when we're done using the iterator.
+        NSMutableArray<ARTRealtimeChannelInternal *> *toFail = [[NSMutableArray alloc] init];
```
Comment (QuintinWillison) [inline Source/ARTRealtime.m]: Please make pointers `const` wherever possible.

File: Source/ARTRealtimeChannel.m [hunk 2]
```diff
@@ -1253,6 +1253,7 @@ - (void)_detach:(void (^)(ARTErrorInfo * _Nullable))callback {
             [_attachedEventEmitter once:^(ARTErrorInfo *errorInfo) {
                 if (callback && errorInfo) {
                     callback(errorInfo);
+                    return;
```
Comment (QuintinWillison) [inline Source/ARTRealtimeChannel.m]: What has this new addition got to do with the purpose of this PR (being iterator avoidance)?

Comment (tcard) [reply Source/ARTRealtimeChannel.m]: Nothing. It's a tangentially related bug fix. I can open a separate PR for it, but the test for the fix that relevant for this PR relies on it, so then I'd introduce a dependency between that PR and this PR.

File: Source/ARTRealtime.m (hunk 1 above)
Comment (tcard) [reply Source/ARTRealtime.m]: Done at db0bc56, but if we're going to have this as a rule,

1. maybe we should write down a style guide or something,
2. why limit it to pointers? (Asking out if ignorance, I'm not familiar with the subtleties involved.)

**Comment by tcard** [comment]
@QuintinWillison Anything outstanding here?

File: Source/ARTRealtimeChannel.m (hunk 2 above)
Comment (QuintinWillison) [reply Source/ARTRealtimeChannel.m]: Let's keep it simple, as is.
